---
- hosts: workers
  gather_facts: false
  become: yes
  tasks:         
  - name: Create rke2 folder
    file: 
      path: /etc/rancher/rke2
      state: directory
  - name: Copy config.yaml
    template: 
      src: templates/config.yaml.j2 
      dest: /etc/rancher/rke2/config.yaml
  - name: Copy registries.yaml
    template:
      src: templates/registries.yaml.j2
      dest: /etc/rancher/rke2/registries.yaml
  - name: Install rancher
    shell: cat /tmp/rke2.yaml | INSTALL_RKE2_VERSION={{ rke2_version }} INSTALL_RKE2_TYPE="agent"  sh -
  - name: Enable rke2-agent.service
    service:
      name: rke2-agent.service
      enabled: yes  
  - name: Start rke2-agent.service
    service:
      name: rke2-agent.service
      state: started     


