---
- hosts: masters
  gather_facts: false
  tasks:
  - name: Copy registries.yaml
    template:
      src: templates/registries.yaml.j2
      dest: /etc/rancher/rke2/registries.yaml
  - name: restart rke2-server.service
    service:
      name: rke2-server.service
      state: restarted

- hosts: workers
  gather_facts: false
  tasks:
  - name: Copy registries.yaml
    template:
      src: templates/registries.yaml.j2
      dest: /etc/rancher/rke2/registries.yaml
  - name: restart rke2-agent.service
    service:
      name: rke2-agent.service
      state: restarted
  - name: reboot machines
    reboot:
